In [25]:
import pandas as pd
import numpy as np

students_with_project_dataset = pd.read_csv('C:\\Users\\USER\\Desktop\\NOUN\\DCS\\2021_2 RESULT\\Computer Science\\M.Sc. Information Technology\\M.Sc. Information Technology with project.csv')
print(len(students_with_project_dataset))
print(students_with_project_dataset.columns)
compulsory_course_set= ['GST807','CIT843','CIT831','CIT853','CIT851','CIT802','CIT854','CIT852','CIT834','CIT899','GST707','CIT743','CIT731','CIT753','CIT751','CIT702','CIT754','CIT752','CIT734','CIT799','GST607','CIT643','CIT631','CIT653','CIT651','CIT602','CIT654','CIT652','CIT634','CIT699']
elective_course_set= {'CIT841','CIT811','CIT891','CIT832','CIT844','CIT741','CIT711','CIT791','CIT732','CIT744','CIT641','CIT611','CIT691','CIT632','CIT644'}
checker = False

course=[]
for i in range(len(students_with_project_dataset)):
    if students_with_project_dataset["Number of Real Outstanding Courses"][i] == 0 and students_with_project_dataset["TCE"][i] >= 35 and students_with_project_dataset["CGPA"][i] >=3.0:
        students_with_project_dataset["Number of Outstanding Compulsory Courses"][i] = "Cleared"
        print(students_with_project_dataset["Number of Outstanding Compulsory Courses"])  
    elif students_with_project_dataset["Number of Real Outstanding Courses"][i] >0 and students_with_project_dataset["CGPA"][i]  >=3.0 and students_with_project_dataset["TCE"][i] >= 35 :
        passed_set = list(students_with_project_dataset["Passed Courses"][i])
        outstanding_set=list(students_with_project_dataset["Real Outstanding Courses"][i])
       
        for item in passed_set:
            for it in outstanding_set:
                if item[4:5] == it[4:5]:
                    outstanding_set.remove(it)
            for item in outstanding_set :
                 if item in compulsory_course_set:
                    checker = True
                    
        if checker != True :
            students_with_project_dataset["Number of Outstanding Compulsory Courses"][i] = "Cleared"
        print(students_with_project_dataset["Number of Outstanding Compulsory Courses"])

484
Index(['Matric Number', 'Name', 'StudyCentre', 'Mobile Number', 'Entry Level',
       'TCC', 'TCE', 'TGPE', 'CGPA', 'Passed Courses', 'Outstanding Courses',
       'Failed Courses', 'Number of Passed Courses',
       'Real Outstanding Courses', 'Number of Real Outstanding Courses',
       'Outstanding Compulsory Courses',
       'Number of Outstanding Compulsory Courses'],
      dtype='object')
0      Cleared
1          TCE
2          TCE
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2          TCE
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object

<ipython-input-25-0913f5866cd0>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_with_project_dataset["Number of Outstanding Compulsory Courses"][i] = "Cleared"
<ipython-input-25-0913f5866cd0>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  students_with_project_dataset["Number of Outstanding Compulsory Courses"][i] = "Cleared"

0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...
479        TCE
480        TCE
481        TCE
482        TCE
483        TCE
Name: Number of Outstanding Compulsory Courses, Length: 484, dtype: object
0      Cleared
1      Cleared
2      Cleared
3          TCE
4          TCE
        ...